### PR TITLE
Try leaving open babel there in Travis build

### PR DESCRIPTION
**Pull request by rwest**
The travis build instructions used to forcibly remove open babel.
This branch does not.
Let's see if it works...

### CODE REVIEW

**Comment by rwest** [comment]
It crashed with a segfault.

The conda list shows:
```
openbabel                 2.4.1            py27hf484d3e_7    rmg
rdkit                     2016.03.4           np111py27_1    rmg
```

**Comment by rwest** [comment]
FWIW, moving the RDKit imports to after other stuff didn't help. It still segfaulted.

**Comment by rwest** [comment]
This time it tried @skrsna's openbabel and rdkit:
```
openbabel                 2.4.1                    py27_6    krsna
pyrdl                     1.1              py27h239603c_0    krsna
rdkit                     2017.09.1.dev20170815          py27_1    krsna
```
but it can't import rdkit, missing system libraries etc
```
OSError: /home/travis/miniconda/envs/tst_env/lib/python2.7/site-packages/rdkit/Chem/../../../../././libRDKitFilterCatalog.so.1: undefined symbol: _ZN5boost7archive18text_iarchive_implINS0_13text_iarchiveEE4loadERNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
```

**Comment by skrsna** [comment]
Yeah, my RDKit build is super old and broken

**Comment by rwest** [comment]
Other thing to try, before I forget, is putting RDKit _first_ in the imports. 

> [Colin]: Open Babel/Pybel after RDKit works for me (edited)

**Comment by rwest** [comment]
No Segfault!!

but...

Some IndexErrors (list index out of range: `template.reactants[1].item`)
Some ImportErrors (eg pybel). Does pybel not come for free with openbabel?

**Comment by skrsna** [comment]
@davidfarinajr has seen these errors before

**Comment by rwest** [comment]
@skrsna does your openbabel binary not have pybel?

**Comment by skrsna** [comment]
> @skrsna does your openbabel binary not have pybel?

I'm not sure and I built openbabel three months ago, so I kinda forgot how I built it. I think I documented the build process somewhere and I'll see if I can resolve that error

**Comment by ndharms** [comment]
This has been addressed in #43 so I'm going to close this

**Pull request closed without merging**
