### PR TITLE
Converted "".format() to f-string literals

### PR DESCRIPTION
**Pull request by rwest**
These are nicer to look at, easier to debug, etc.

I did these using the "convert to f-string literal" code intention
in PyCharm. Click inside a .format() string somewhere and press
Alt-Enter on your keyboard, then select "convert to f-string literal".

This first commit I just did a couple of files.

There are probably some tools to do it faster than one at a time,
like https://github.com/asottile/pyupgrade

Think about when best to do this in regards other open pull requests, to minimize merge conflicts.
But I think it's worth doing - either with one concerted effort or gradually as you touch code.

### CODE REVIEW

**Comment by ndharms** [comment]
Definitely a good move with this PR. But after browsing through the Travis CI for the branch, it looks like `.format` was substituted with `.` rather than nothing. Thanks for the effort though!

**Comment by rwest** [comment]
Fixed the mistake (I had done one by hand because it was split across lines, and made a manual error).
So I think this shows the PyCharm method is quite effective.
Although it reduces it to a few clicks/keystrokes per instance, you still have to do each instance separately, so it might be worth looking into a wholesale approach.

Either way, I'll leave this here for you to decide when best to do it, in relation to your other changes.

**Comment by ndharms** [comment]
I'm liking f-strings as opposed to .format so I think we should work on this. I've also looking into a package called flynt and it's doing a good job on this. I'm working on some of this right now and I'l push some changes in a bit.

**Comment by ndharms** [comment]
Okay, just pushed some changes, let me know thoughts

**Review by rwest — COMMENTED** [review]
Skimming the diff on my phone it all looks good.

**Comment by ndharms** [comment]
Fixed a couple of typos and did a rebase to truncate those into their proper PRs. Let's see how the tests go but I think it should be ready to merge in shortly

**Comment by ndharms** [comment]
Okay, tests pass and everything's looking good. Unless @davidfarinajr has any complaints, I'll merge this in shortly

**Comment by ndharms** [comment]
Well, there's also the codecov/patch not passing... but that doesn't really bother me too much.

**Comment by davidfarinajr** [comment]
Sorry, not sure how I missed this earlier today. Looks good, you can merge.

**Pull request merged**
